version: "3"
services:
  scoopi-node-1:
      image: codetab/scoopi:latest
      container_name: scoopi-node-1
      environment:
          - "TZ=Asia/Kolkata"
          - "JAVA_OPTS=-Dscoopi.cluster.enable=true -Dscoopi.cluster.config.file=/hazelcast-multicast.xml" 
      volumes:
          - ./defs:/scoopi/defs
          - ./conf:/scoopi/conf
          - ./data:/scoopi/data
          - ./logs:/scoopi/logs
          - ./output:/scoopi/output
  scoopi-node-2:
      image: codetab/scoopi:latest
      container_name: scoopi-node-2
      environment:
          - "TZ=Asia/Kolkata"
          - "JAVA_OPTS=-Dscoopi.cluster.enable=true -Dscoopi.cluster.config.file=/hazelcast-multicast.xml" 
      volumes:
          - ./defs:/scoopi/defs
          - ./conf:/scoopi/conf
          - ./data:/scoopi/data
          - ./logs:/scoopi/logs
          - ./output:/scoopi/output
  scoopi-node-3:
      image: codetab/scoopi:latest
      container_name: scoopi-node-3
      ports:
          - "9010:9010"
      environment:
          - "TZ=Asia/Kolkata"
          - "JAVA_OPTS=-Dscoopi.cluster.enable=true -Dscoopi.cluster.config.file=/hazelcast-multicast.xml" 
      volumes:
          - ./defs:/scoopi/defs
          - ./conf:/scoopi/conf
          - ./data:/scoopi/data
          - ./logs:/scoopi/logs
          - ./output:/scoopi/output

