version: "3"
services:
  scoopi-db:
      image: mariadb:10.3
      container_name: scoopi-db
      command: 
          --log_warnings=1
          --lower_case_table_names=1
          --innodb-compression-default=1
          --innodb_compression_algorithm=zlib
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=scoopi
      ports:
          - "3306:3306"
      volumes:
          - ./data:/var/lib/mysql
          - ./docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  scoopi:
      image: codetab/scoopi:latest 
      container_name: scoopi
      depends_on:
          - scoopi-db
      ports:
          - "9010:9010"
      volumes:
          - ./defs:/scoopi/defs
          - ./conf:/scoopi/conf
          - ./logs:/scoopi/logs
          - ./output:/scoopi/output
