version: "3"
services:
  scoopi:
      image: codetab/scoopi:latest 
      container_name: scoopi
      ports:
          - "9010:9010"
      volumes:
          - ./defs:/scoopi/defs
          - ./conf:/scoopi/conf
          - ./data:/scoopi/data
          - ./logs:/scoopi/logs
          - ./output:/scoopi/output
