## dev and test db

version: "3"
services:
  scoopi-dev-nginx:
      image: nginx:latest
      container_name: scoopi-dev-nginx 
      ports:
          - "80:80"
      volumes:
          - ./nginx/www:/usr/share/nginx/html:ro
          - ./nginx/conf.d:/etc/nginx/conf.d:ro  

